import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import '../constants/api_constants.dart';
import '../network/dio_client.dart';

/// Gemini Vision AI Service for Multimodal OCR and Medication Label Extraction
class GeminiService {
  final DioClient _dioClient;

  GeminiService({DioClient? dioClient}) : _dioClient = dioClient ?? DioClient();

  String get _apiKey => dotenv.env['GEMINI_API_KEY'] ?? '';

  /// Scans medication package image bytes and returns structured medication details
  Future<Map<String, dynamic>> scanMedicationLabel(Uint8List imageBytes) async {
    final base64Image = base64Encode(imageBytes);

    const promptText = '''
You are an expert clinical pharmacist and medication OCR system. Analyze the provided image of a medication package or prescription label.
Extract the following information in strict JSON format:
{
  "brandName": "Brand name or commercial name",
  "genericName": "Active ingredient / generic chemical name",
  "dosage": "Strength per unit (e.g. 500mg, 10mg/mL)",
  "frequency": "Recommended frequency (e.g. Once daily, Twice daily, Every 8 hours)",
  "suggestedTimes": ["08:00", "20:00"],
  "instructions": "Specific administration instructions (e.g. Take with food)",
  "warnings": "Key precautions or contraindications",
  "confidenceScore": 0.95
}
Return ONLY valid raw JSON with no Markdown backticks.
''';

    final requestBody = {
      "contents": [
        {
          "parts": [
            {"text": promptText},
            {
              "inline_data": {
                "mime_type": "image/jpeg",
                "data": base64Image,
              }
            }
          ]
        }
      ],
      "generationConfig": {
        "temperature": 0.1,
        "response_mime_type": "application/json",
      }
    };

    final response = await _dioClient.post(
      '${ApiConstants.geminiVisionEndpoint}?key=$_apiKey',
      data: requestBody,
    );

    final candidates = response.data['candidates'] as List?;
    if (candidates == null || candidates.isEmpty) {
      throw Exception('No analysis result generated by Gemini AI');
    }

    final textResult =
        candidates[0]['content']['parts'][0]['text'] as String;
    return jsonDecode(textResult) as Map<String, dynamic>;
  }
}
